apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reverse-pods
    spec:
      containers:
      - image: kugelr/reverse:latest
        name: reverse-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http-server
